os: Visual Studio 2017

platform:
    - x64
    - x86

cache:
    - sw -> win-ci.py

environment:
    matrix:
        - PY: 37


build_script:
    - ps: |
        If ($env:Platform -Match "x86") {
            $env:VCVARS_PLATFORM="32"
            $env:PYTHON="C:/Python$env:PY"
        } Else {
            $env:VCVARS_PLATFORM="64"
            $env:PYTHON="C:/Python$env:PY-x64"
        }
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars%VCVARS_PLATFORM%.bat"
    - set PATH=%PYTHON%;%PATH%
    - python -c "import sys; print(sys.version_info); import platform; print(platform.architecture())"

test_script:
    - python.exe setup.py test
