language: python
python:
  - "3.6"
  - "3.5"
  - "2.7"
install: pip install cpp-coveralls
script: CFLAGS="--coverage -DDUK_OPT_ASSERTIONS" python setup.py test
after_success:
  - coveralls -E '.*/src/duktape'
sudo: false
